### ISSUE TITLE
Build fail only with cargo_asan

### ISSUE THREAD

**Issue by bronte000** [kaist-cp/cs431#577]
![image](https://user-images.githubusercontent.com/48073703/145411680-def9297a-1f60-4b21-937d-464eb7e8f6a1.png)
![image](https://user-images.githubusercontent.com/48073703/145469656-9f6f327f-c5e1-4543-ade5-b80b6213415c.png)
![image](https://user-images.githubusercontent.com/48073703/145469714-1816227b-137d-4f26-95d2-f75c0720b3f1.png)

My code works well with cargo and cargo-release.
Actually, it passed all tests including sync tests. (I get 30/100 by passing all sync tests)
But it does not compile with cargo_asan. 

![image](https://user-images.githubusercontent.com/48073703/145469789-39399d06-b6ad-4da1-b255-0a50c0621bb9.png)
It was same with grading server.
It seems that compiling my code takes too much time.

I have no idea..
What should I do?
Is there any condition to use cargo_assan?

**Comment by bronte000** [comment]
![image](https://user-images.githubusercontent.com/48073703/145471117-4d9d0484-be61-4c66-a4fa-230f4a39bba6.png)

Here is the error message showed when I compile it with senitizer

**Comment by bronte000** [comment]
It seems template code does not compile either.
The result was same even though I stashed all changes and compiled the template code.

![image](https://user-images.githubusercontent.com/48073703/145472070-fa528f9c-e11e-484f-a216-5e886c33fc80.png)

**Comment by bronte000** [comment]
I realized that I chose Assignment label accidently, but it was impossible to fix label after creating issue...
Sorry for confuse.

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs431/issues/549#issuecomment-990514617

**Comment by tomtomjhj** [comment]
Ah sorry, it seems that there is a bug in the grader script. I'll fix this asap

**Comment by tomtomjhj** [comment]
Fixed by https://github.com/kaist-cp/cs431/commit/bcc8dc4a3afeafbfba12ca97a0d8512e01a75782

**Comment by bronte000** [comment]
Actually it still does not compile with local compiler.
![image](https://user-images.githubusercontent.com/48073703/145520257-45094935-978f-4bc3-a51d-43299bd0bac2.png)

But grading server now works! I got full score on the server.
Thank you for fast fix.

**Comment by tomtomjhj** [comment]
You're using something other than x86_64-unknown-linux-gnu, right?
I guess I should update the grader script to adapt to the platform, or at least document that it doesn't support other platforms..
